#ifndef LOGLOGGINGCATEGORIES_H
#define LOGLOGGINGCATEGORIES_H
#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logDebug)
Q_DECLARE_LOGGING_CATEGORY(logInfo)
Q_DECLARE_LOGGING_CATEGORY(logWarning)
Q_DECLARE_LOGGING_CATEGORY(logCritical)

#endif // LOGLOGGINGCATEGORIES_H
