
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MYMASTER_H
#define MYMASTER_H

#include "can/festival/inc/data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 MyMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * MyMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data MyMaster_Data;
extern UNS8 E14DCLinkRelay;		/* Mapped at index 0x280E, subindex 0x00*/
extern UNS8 E48DeviceControlState;		/* Mapped at index 0x2830, subindex 0x00*/
extern UNS8 I85TargetReached;		/* Mapped at index 0x3055, subindex 0x00*/
extern UNS8 I201MotionStatusByte;		/* Mapped at index 0x30C9, subindex 0x00*/
extern INTEGER32 I203CurrentPosition;		/* Mapped at index 0x30CB, subindex 0x00*/
extern UNS16 I210PosiControlWord;		/* Mapped at index 0x30D2, subindex 0x00*/
extern UNS8 I211MotionCommandByte;		/* Mapped at index 0x30D3, subindex 0x00*/
extern INTEGER32 I213TargetPosition;		/* Mapped at index 0x30D5, subindex 0x00*/
extern INTEGER16 I215VFactor;		/* Mapped at index 0x30D7, subindex 0x00*/
extern UNS16 Controlword;		/* Mapped at index 0x6040, subindex 0x00*/
extern UNS16 Statusword;		/* Mapped at index 0x6041, subindex 0x00*/

#endif // MYMASTER_H
