
/* File generated by gen_cfile.py. Should not be modified. */

#include "MyMaster.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 E14DCLinkRelay = 0x0;		/* Mapped at index 0x280E, subindex 0x00 */
UNS8 E48DeviceControlState = 0x0;		/* Mapped at index 0x2830, subindex 0x00 */
UNS8 I85TargetReached = 0x1;		/* Mapped at index 0x3055, subindex 0x00 */
UNS8 I201MotionStatusByte = 0x0;		/* Mapped at index 0x30C9, subindex 0x00 */
INTEGER32 I203CurrentPosition = 0x0;		/* Mapped at index 0x30CB, subindex 0x00 */
UNS16 I210PosiControlWord = 0x0;		/* Mapped at index 0x30D2, subindex 0x00 */
UNS8 I211MotionCommandByte = 0x0;		/* Mapped at index 0x30D3, subindex 0x00 */
INTEGER32 I213TargetPosition = 0x0;		/* Mapped at index 0x30D5, subindex 0x00 */
INTEGER16 I215VFactor = 0x0;		/* Mapped at index 0x30D7, subindex 0x00 */
UNS16 Controlword = 0xF;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 MyMaster_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 MyMaster_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 MyMaster_iam_a_slave = 0;

TIMER_HANDLE MyMaster_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 MyMaster_obj1000 = 0x0;	/* 0 */
                    subindex MyMaster_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&MyMaster_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 MyMaster_obj1001 = 0x0;	/* 0 */
                    subindex MyMaster_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MyMaster_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 MyMaster_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 MyMaster_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t MyMaster_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex MyMaster_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&MyMaster_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&MyMaster_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 MyMaster_obj1005 = 0x40000080;	/* 1073741952 */
                    ODCallback_t MyMaster_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex MyMaster_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&MyMaster_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 MyMaster_obj1006 = 0xFF50;	/* 50000 */
                    ODCallback_t MyMaster_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex MyMaster_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&MyMaster_obj1006 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 MyMaster_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 MyMaster_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 MyMaster_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 MyMaster_highestSubIndex_obj1016 = 0;
                    UNS32 MyMaster_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 MyMaster_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 MyMaster_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 MyMaster_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 MyMaster_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 MyMaster_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 MyMaster_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex MyMaster_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MyMaster_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&MyMaster_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&MyMaster_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&MyMaster_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&MyMaster_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 MyMaster_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 MyMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 MyMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 MyMaster_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex MyMaster_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MyMaster_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&MyMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&MyMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&MyMaster_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 MyMaster_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 MyMaster_obj1400_COB_ID_used_by_PDO = 0x201;	/* 512 */
                    UNS8 MyMaster_obj1400_Transmission_Type = 0x1;	/* 1 */
                    UNS16 MyMaster_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MyMaster_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MyMaster_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 MyMaster_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex MyMaster_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MyMaster_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&MyMaster_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&MyMaster_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&MyMaster_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&MyMaster_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&MyMaster_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&MyMaster_obj1400_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 MyMaster_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 MyMaster_obj1600[] = 
                    {
                      0x60410010,	/* 1614872592 */
                      0x30C90008	/* 818479112 */
                    };
                    subindex MyMaster_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MyMaster_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&MyMaster_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&MyMaster_obj1600[1] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 MyMaster_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 MyMaster_obj1800_COB_ID_used_by_PDO = 0x181;	/* 384 */
                    UNS8 MyMaster_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MyMaster_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MyMaster_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MyMaster_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 MyMaster_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t MyMaster_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex MyMaster_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MyMaster_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&MyMaster_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&MyMaster_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&MyMaster_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&MyMaster_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&MyMaster_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&MyMaster_obj1800_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 MyMaster_highestSubIndex_obj1A00 = 3; /* number of subindex - 1*/
                    UNS32 MyMaster_obj1A00[] = 
                    {
                      0x60400010,	/* 1614807056 */
                      0x30D20010,	/* 819068944 */
                      0x30D50020	/* 819265568 */
                    };
                    subindex MyMaster_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MyMaster_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&MyMaster_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&MyMaster_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&MyMaster_obj1A00[2] }
                     };

/* index 0x280E :   Mapped variable E14DCLinkRelay */
                    subindex MyMaster_Index280E[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&E14DCLinkRelay }
                     };

/* index 0x2830 :   Mapped variable E48DeviceControlState */
                    subindex MyMaster_Index2830[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&E48DeviceControlState }
                     };

/* index 0x3055 :   Mapped variable I85TargetReached */
                    subindex MyMaster_Index3055[] = 
                     {
                       { RO|TO_BE_SAVE, boolean, sizeof (UNS8), (void*)&I85TargetReached }
                     };

/* index 0x30C9 :   Mapped variable I201MotionStatusByte */
                    ODCallback_t I201MotionStatusByte_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex MyMaster_Index30C9[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&I201MotionStatusByte }
                     };

/* index 0x30CB :   Mapped variable I203CurrentPosition */
                    subindex MyMaster_Index30CB[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&I203CurrentPosition }
                     };

/* index 0x30D2 :   Mapped variable I210PosiControlWord */
                    subindex MyMaster_Index30D2[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&I210PosiControlWord }
                     };

/* index 0x30D3 :   Mapped variable I211MotionCommandByte */
                    subindex MyMaster_Index30D3[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&I211MotionCommandByte }
                     };

/* index 0x30D5 :   Mapped variable I213TargetPosition */
                    subindex MyMaster_Index30D5[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&I213TargetPosition }
                     };

/* index 0x30D7 :   Mapped variable I215VFactor */
                    subindex MyMaster_Index30D7[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&I215VFactor }
                     };

/* index 0x6040 :   Mapped variable Controlword */
                    subindex MyMaster_Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Controlword }
                     };

/* index 0x6041 :   Mapped variable Statusword */
                    ODCallback_t Statusword_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex MyMaster_Index6041[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Statusword }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable MyMaster_objdict[] = 
{
  { (subindex*)MyMaster_Index1000,sizeof(MyMaster_Index1000)/sizeof(MyMaster_Index1000[0]), 0x1000},
  { (subindex*)MyMaster_Index1001,sizeof(MyMaster_Index1001)/sizeof(MyMaster_Index1001[0]), 0x1001},
  { (subindex*)MyMaster_Index1005,sizeof(MyMaster_Index1005)/sizeof(MyMaster_Index1005[0]), 0x1005},
  { (subindex*)MyMaster_Index1006,sizeof(MyMaster_Index1006)/sizeof(MyMaster_Index1006[0]), 0x1006},
  { (subindex*)MyMaster_Index1018,sizeof(MyMaster_Index1018)/sizeof(MyMaster_Index1018[0]), 0x1018},
  { (subindex*)MyMaster_Index1280,sizeof(MyMaster_Index1280)/sizeof(MyMaster_Index1280[0]), 0x1280},
  { (subindex*)MyMaster_Index1400,sizeof(MyMaster_Index1400)/sizeof(MyMaster_Index1400[0]), 0x1400},
  { (subindex*)MyMaster_Index1600,sizeof(MyMaster_Index1600)/sizeof(MyMaster_Index1600[0]), 0x1600},
  { (subindex*)MyMaster_Index1800,sizeof(MyMaster_Index1800)/sizeof(MyMaster_Index1800[0]), 0x1800},
  { (subindex*)MyMaster_Index1A00,sizeof(MyMaster_Index1A00)/sizeof(MyMaster_Index1A00[0]), 0x1A00},
  { (subindex*)MyMaster_Index280E,sizeof(MyMaster_Index280E)/sizeof(MyMaster_Index280E[0]), 0x280E},
  { (subindex*)MyMaster_Index2830,sizeof(MyMaster_Index2830)/sizeof(MyMaster_Index2830[0]), 0x2830},
  { (subindex*)MyMaster_Index3055,sizeof(MyMaster_Index3055)/sizeof(MyMaster_Index3055[0]), 0x3055},
  { (subindex*)MyMaster_Index30C9,sizeof(MyMaster_Index30C9)/sizeof(MyMaster_Index30C9[0]), 0x30C9},
  { (subindex*)MyMaster_Index30CB,sizeof(MyMaster_Index30CB)/sizeof(MyMaster_Index30CB[0]), 0x30CB},
  { (subindex*)MyMaster_Index30D2,sizeof(MyMaster_Index30D2)/sizeof(MyMaster_Index30D2[0]), 0x30D2},
  { (subindex*)MyMaster_Index30D3,sizeof(MyMaster_Index30D3)/sizeof(MyMaster_Index30D3[0]), 0x30D3},
  { (subindex*)MyMaster_Index30D5,sizeof(MyMaster_Index30D5)/sizeof(MyMaster_Index30D5[0]), 0x30D5},
  { (subindex*)MyMaster_Index30D7,sizeof(MyMaster_Index30D7)/sizeof(MyMaster_Index30D7[0]), 0x30D7},
  { (subindex*)MyMaster_Index6040,sizeof(MyMaster_Index6040)/sizeof(MyMaster_Index6040[0]), 0x6040},
  { (subindex*)MyMaster_Index6041,sizeof(MyMaster_Index6041)/sizeof(MyMaster_Index6041[0]), 0x6041},
};

const indextable * MyMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = MyMaster_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = MyMaster_Index1006_callbacks; break;
		case 0x1018: i = 4;break;
		case 0x1280: i = 5;break;
		case 0x1400: i = 6;break;
		case 0x1600: i = 7;break;
		case 0x1800: i = 8;*callbacks = MyMaster_Index1800_callbacks; break;
		case 0x1A00: i = 9;break;
		case 0x280E: i = 10;break;
		case 0x2830: i = 11;break;
		case 0x3055: i = 12;break;
		case 0x30C9: i = 13;*callbacks = I201MotionStatusByte_callbacks; break;
		case 0x30CB: i = 14;break;
		case 0x30D2: i = 15;break;
		case 0x30D3: i = 16;break;
		case 0x30D5: i = 17;break;
		case 0x30D7: i = 18;break;
		case 0x6040: i = 19;break;
		case 0x6041: i = 20;*callbacks = Statusword_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &MyMaster_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status MyMaster_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index MyMaster_firstIndex = {
  0, /* SDO_SVR */
  5, /* SDO_CLT */
  6, /* PDO_RCV */
  7, /* PDO_RCV_MAP */
  8, /* PDO_TRS */
  9 /* PDO_TRS_MAP */
};

const quick_index MyMaster_lastIndex = {
  0, /* SDO_SVR */
  5, /* SDO_CLT */
  6, /* PDO_RCV */
  7, /* PDO_RCV_MAP */
  8, /* PDO_TRS */
  9 /* PDO_TRS_MAP */
};

const UNS16 MyMaster_ObjdictSize = sizeof(MyMaster_objdict)/sizeof(MyMaster_objdict[0]); 

CO_Data MyMaster_Data = CANOPEN_NODE_DATA_INITIALIZER(MyMaster);

